### ISSUE TITLE
global name 'maketrans' is not defined

### ISSUE THREAD

**Issue by fburdet** [BradnerLab/pipeline#50]
Hello,

When running
python bamToGFF.py -e 200 -r -m 1 -b myBam.bam -i myGFF.gff -o myOutput.gff
I get a 

[1;31mNameError[0m: global name 'maketrans' is not defined

Can you please check?

**Comment by jdimatteo** [comment]
@fburdet this should be fixed now -- can you do a git pull and verify?

**Comment by jdimatteo** [comment]
@bradnerComputation / Charles: does Bradner Lab still use bamToGFF.py ? Do you instead always use `bamliquidator_batch.py --match_bamToGFF`?  It seems like this maketrans error has been there since ae86f8a in May 2014.  I fixed the error since it was trivial (see 0467ae9).

Charles, can you please advise @fburdet if bamToGFF.py should no longer be used?

**Comment by bradnerComputation** [comment]
Hi @fburdet bamToGFF.py is deprecated and is no longer being used by our lab. I would recommend installing bamliquidator instead:

https://github.com/BradnerLab/pipeline/wiki/bamliquidator
