### ISSUE TITLE
bamliquidator: Installation issues

### ISSUE THREAD

**Issue by venuthatikonda** [BradnerLab/pipeline#57]
Hi,

I have been trying to install `bamliquidator`. I added `CPATH` and `LIBRARY_PATH` as described [here](https://github.com/BradnerLab/pipeline/wiki/bamliquidator#developers) and added `samtools` in `CPATH` directory. But when I use the command `make`, it is giving the following error

```
g++ -std=c++0x -O3 -g -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -c bamliquidator.m.cpp
In file included from bamliquidator.h:4:0,
                 from bamliquidator.m.cpp:7:
/usr/local/include/samtools/sam.h:28:24: fatal error: htslib/sam.h: No such file or directory
 #include "htslib/sam.h"
                        ^
compilation terminated.
makefile:96: recipe for target 'bamliquidator.m.o' failed
make: *** [bamliquidator.m.o] Error 1
```

I would appreciate your clarification on this issue.

Thank you.

**Comment by jdimatteo** [comment]
Hi venuthatikonda, very sorry for the delayed response.

bamliquidator expects samtools version 0.1.19, e.g. as installed by the Ubuntu 14.04 package libbam-dev.  Your build is failing because g++ is finding a newer version of samtools.

Please try the following from the pipeline/bamliquidator_internal directory:

```
make clean
CPLUS_INCLUDE_PATH=/usr/include make
```

If that doesn't help, please provide the output of `cat /etc/issue` and I'll follow up further.  Also, you may consider using the pre-compiled binaries by following these instructions instead: https://github.com/BradnerLab/pipeline/wiki/motif_liquidator#1-download (just extract the contents with those binaries into your bamliquidator_internal directory).

**Comment by venuthatikonda** [comment]
Hi John,

Thanks for the suggestions. I will update here once I follow the above instruction.

**Comment by datakid** [comment]
Is there any chance that this will be updated to the latest samtools (1.6 atm)? I am installing these by hand, so it's no issue, but that is a very old samtools

**Comment by datakid** [comment]
motif liquidator looks ok, but bamliquidator is explicitly listed as a dependency for [Rose2](https://github.com/linlabbcm/rose2) and [coltron](https://pypi.python.org/pypi/coltron) :/

**Comment by jdimatteo** [comment]
@datakid sorry, I don't have any plans to upgrade to latest samtools, but patches are welcome

**Comment by jdimatteo** [comment]
Closing because this issue is very old and I hope I addressed the original questions.  If there are additional questions, please open a new issue.
